### ISSUE TITLE
集成到脚本里面抛出异常

### ISSUE THREAD

**Issue by rachpt** [Aruelius/cloud189#31]
```sh
#!/bin/bash
# filename: upload.sh
cloud189='/home/path/to/cloud189/main.py'
cd "/mnt/data/movies/"
for i in `ls`;
do
  echo "uplaod $i" >> /mnt/data/up.log
  $cloud189 upload "/mnt/data/movies/$i"
done
```
`nohup ./upload.sh &> /path/to/log &`

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/path/to/cloud189/cloud189/cli/manager.py", line 16, in foo
    input_with_timeput_ans = input()
OSError: [Errno 9] Bad file des
```

**Comment by rachpt** [comment]
fixed.
