### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by linker999** [Aruelius/cloud189#32]
版本是3.8.1 没错哦 
root@link:~/cloud189# python3 main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from cloud189.cli.cli import Commander
  File "/root/cloud189/cloud189/cli/cli.py", line 13, in <module>
    from cloud189.cli.downloader import Downloader, Uploader
  File "/root/cloud189/cloud189/cli/downloader.py", line 7, in <module>
    from cloud189.cli.utils import why_error
  File "/root/cloud189/cloud189/cli/utils.py", line 6, in <module>
    import readline
  File "/opt/lib/python3.8/site-packages/readline.py", line 6, in <module>
    from pyreadline.rlmain import Readline
  File "/opt/lib/python3.8/site-packages/pyreadline/__init__.py", line 12, in <module>
    from . import logger, clipboard, lineeditor, modes, console
  File "/opt/lib/python3.8/site-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
    from .win32_clipboard import GetClipboardText, SetClipboardText
  File "/opt/lib/python3.8/site-packages/pyreadline/clipboard/win32_clipboard.py", line 37, in <module>
    import ctypes.wintypes as wintypes
  File "/wintypes.py", line 20, in <module>
ValueError: _type_ 'v' not supported

**Comment by Aruelius** [comment]
https://github.com/Aruelius/cloud189#jump
请同学们认真阅读 README

**Comment by linker999** [comment]
> https://github.com/Aruelius/cloud189#jump
> 请同学们认真阅读 README
。。要安装的有点多 ，我是用群晖系统，这个还真的不知道怎么安装

**Comment by Aruelius** [comment]
> > https://github.com/Aruelius/cloud189#jump
> > 请同学们认真阅读 README
> > 。。要安装的有点多 ，我是用群晖系统，这个还真的不知道怎么安装

安装的有点多？就一个依赖。
用 ipkg 安装。

**Comment by linker999** [comment]
> > > https://github.com/Aruelius/cloud189#jump
> > > 请同学们认真阅读 README
> > > 。。要安装的有点多 ，我是用群晖系统，这个还真的不知道怎么安装
> 
> 安装的有点多？就一个依赖。
> 用 ipkg 安装。

可惜 ipkg安装的python3版本只有3.7

**Comment by Aruelius** [comment]
> > > > https://github.com/Aruelius/cloud189#jump
> > > > 请同学们认真阅读 README
> > > > 。。要安装的有点多 ，我是用群晖系统，这个还真的不知道怎么安装
> > 
> > 
> > 安装的有点多？就一个依赖。
> > 用 ipkg 安装。
> 
> 可惜 ipkg安装的python3版本只有3.7

可以自行编译 Python3.8
