### ISSUE TITLE
登陆报错

### ISSUE THREAD

**Issue by Mavacer** [Aruelius/cloud189#39]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    commander.login(("--auto", ))
  File "/home/maver/cloud189/cloud189/cli/cli.py", line 109, in login
    code = self._disk.login(username, password)
  File "/home/maver/cloud189/cloud189/api/core.py", line 144, in login
    captchaToken, returnUrl, paramId = self._redirect()
  File "/home/maver/cloud189/cloud189/api/core.py", line 98, in _redirect
    captchaToken = re.findall(r"captchaToken' value='(.+?)'", r.text)[0]
AttributeError: 'NoneType' object has no attribute 'text'
能运行，输完账密报了这个错，然后就崩了
大佬求解

**Comment by Mavacer** [comment]
修好了。。。。缺依赖
