### ISSUE TITLE
运行错误哦

### ISSUE THREAD

**Issue by Qa7060123** [Aruelius/cloud189#42]
ubuntu@127:~/github/cloud189-master$ sudo python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from cloud189.cli.cli import Commander
  File "/home/ubuntu/github/cloud189-master/cloud189/cli/cli.py", line 242
    if file := self._file_list.find_by_name(fname):
             ^
SyntaxError: invalid syntax

**Comment by Aruelius** [comment]
请将 Python 版本升级为 Python 3.8 及以上。
