### ISSUE TITLE
老板，直接运行python3.8 main.py会报错

### ISSUE THREAD

**Issue by kaine1973** [Aruelius/cloud189#43]
报的是permission denied。你的脚本直接把文件写入到根目录了。普通用户是不行的，加了python3.8 ./main.py 就可以运行了。但是你的readme里面写的样例就是python3.8 main.py。所以我猜你用的是root权限运行的

**Comment by kaine1973** [comment]
kaidan@Kaidans-iMac cloud189 % python3.8 main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from cloud189.cli.cli import Commander
  File "/Users/kaidan/Programs/cloud189/cloud189/cli/cli.py", line 8, in <module>
    from cloud189.api import Cloud189
  File "/Users/kaidan/Programs/cloud189/cloud189/api/__init__.py", line 1, in <module>
    from cloud189.api.core import Cloud189
  File "/Users/kaidan/Programs/cloud189/cloud189/api/core.py", line 16, in <module>
    from cloud189.api.utils import *
  File "/Users/kaidan/Programs/cloud189/cloud189/api/utils.py", line 23, in <module>
    logging.basicConfig(level=logging.DEBUG,
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1976, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/debug-cloud189.log'

**Comment by rachpt** [comment]
这一行兼容性较差，
https://github.com/Aruelius/cloud189/blob/a444dc410cf39dd62bfe3e909813dfd2b88a9e12/cloud189/api/utils.py#L21
晚上下班后我更新一下。
main.py 用相对路径或者绝对路径，先。
