### ISSUE TITLE
登陆显示错误

### ISSUE THREAD

**Issue by niu12503** [Aruelius/cloud189#47]
root@sd-128408:~/cloud189-master# python3 main.py 
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from cloud189.cli.cli import Commander
  File "/root/cloud189-master/cloud189/cli/__init__.py", line 1, in <module>
    from cloud189.cli.config import config
  File "/root/cloud189-master/cloud189/cli/config.py", line 3, in <module>
    from cloud189.api.utils import ROOT_DIR
  File "/root/cloud189-master/cloud189/api/__init__.py", line 1, in <module>
    from cloud189.api.core import Cloud189
  File "/root/cloud189-master/cloud189/api/core.py", line 8, in <module>
    import simplejson
ModuleNotFoundError: No module named 'simplejson'

**Comment by Aruelius** [comment]
执行一下
`pip install simplejson`

**Comment by niu12503** [comment]
root@sd-128408:~/cloud189-master# pip install simplejson
Requirement already satisfied: simplejson in /usr/local/lib/python2.7/dist-packages

**Comment by Aruelius** [comment]
`pip3 install simplejson`

**Comment by niu12503** [comment]
root@sd-128408:~# pip3 install simplejson
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

**Comment by Aruelius** [comment]
`apt-get install python-apt`
