### ISSUE TITLE
上传出错

### ISSUE THREAD

**Issue by wanlyg** [Aruelius/cloud189#54]
`全部文件 > Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/requests/adapters.py", line 479, in send
    r = low_conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/requests/adapters.py", line 482, in send
    r = low_conn.getresponse()
  File "/usr/local/python3/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/root/cloud189/cloud189/cli/downloader.py", line 232, in run
    infos = self._disk.upload_dir(self._up_path, self._folder_id, self._force, self._mkdir,
  File "/root/cloud189/cloud189/api/core.py", line 736, in upload_dir
    up_code = self.upload_file(upload_file[0], upload_file[1], force=force, callback=callback)
  File "/root/cloud189/cloud189/api/core.py", line 674, in upload_file
    return self._upload_file_by_client(up_info)
  File "/root/cloud189/cloud189/api/core.py", line 549, in _upload_file_by_client
    code = self._upload_file_data(file_upload_url, upload_file_id, up_info)
  File "/root/cloud189/cloud189/api/core.py", line 481, in _upload_file_data
    resp = requests.put(url, data=post_data, headers=headers, verify=False, timeout=None)
  File "/usr/local/python3/lib/python3.9/site-packages/requests/api.py", line 134, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: Remote end closed connection without response
全部文件 > jobs`

客户端centos7 
版本0.0.5
文件大小300m-1G
只有几个文件成功上传
python3.8.2和python3.9.1都有错误
小文件好像可以

**Comment by Aruelius** [comment]
大文件好像需要分块上传，这种情况会出现在网络不好的时候，后面等我看看怎么优化上传吧（咕咕咕）
