### ISSUE TITLE
运行出错，下的python3.8   pip是3.5

### ISSUE THREAD

**Issue by Qa70601234** [Aruelius/cloud189#55]
ubuntu@ubuntu:~/github/cloud189$ python3.8 main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from cloud189.cli.cli import Commander
  File "/home/ubuntu/github/cloud189/cloud189/cli/cli.py", line 8, in <module>
    from cloud189.api import Cloud189
  File "/home/ubuntu/github/cloud189/cloud189/api/__init__.py", line 1, in <module>
    from cloud189.api.core import Cloud189
  File "/home/ubuntu/github/cloud189/cloud189/api/core.py", line 12, in <module>
    from requests_toolbelt import MultipartEncoder, MultipartEncoderMonitor
ModuleNotFoundError: No module named 'requests_toolbelt'

**Comment by Aruelius** [comment]
安装依赖
https://github.com/Aruelius/cloud189#%E5%87%86%E5%A4%87
