### ISSUE TITLE
上传时出现BrokenPipeError

### ISSUE THREAD

**Issue by deskmonster** [Aruelius/cloud189#9]
作者你好，
首先感谢你编写的cli，不过我在使用的时候遇到了一个问题。在我开始上传文件一段时间后，他会报出BrokenPipeError的错误：
```
Traceback (most recent call last):
  File "189.py", line 295, in <module>
    upload(sys.argv[2])
  File "189.py", line 244, in upload
    upload_file()
  File "189.py", line 240, in upload_file
    "Content-Type": multipart_data.content_type
  File "/home/user/.local/lib/python3.6/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
```
我重试了几次都是这样，不如原因为何。
我的环境是：Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-169-generic x86_64) 与 Python 3.6.10
我上传的文件大小为：14.5GB

**Comment by Aruelius** [comment]
文件大小是多大的？

**Comment by Aruelius** [comment]
> > 文件大小是多大的？
> 
> 我上传的文件大小为：14.5GB

说明文件太大了

**Comment by scatking** [comment]
> 
> 
> > > 文件大小是多大的？
> > 
> > 
> > 我上传的文件大小为：14.5GB
> 
> 说明文件太大了

通常来说，这一般是哪方面的原因引起的呢？
天翼云服务的限制，requests模块的限制还是说因为网络波动的原因?

**Comment by Aruelius** [comment]
![image](https://user-images.githubusercontent.com/25380989/80723948-d583d080-8b33-11ea-8b6c-da65a2b97675.png)

 看起来我这里是可以上传的。

**Comment by scatking** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/25380989/80723948-d583d080-8b33-11ea-8b6c-da65a2b97675.png)
> 
> 看起来我这里是可以上传的。

我这里也是这个界面，但是过了二三十分钟就会报错，可能是因为我这里网络波动吧。

**Comment by Aruelius** [comment]
> > ![image](https://user-images.githubusercontent.com/25380989/80723948-d583d080-8b33-11ea-8b6c-da65a2b97675.png)
> > 看起来我这里是可以上传的。
> 
> 我这里也是这个界面，但是过了二三十分钟就会报错，可能是因为我这里网络波动吧。

如果网页上传没有问题的话，那应该就是程序的问题。

**Comment by scatking** [comment]
我今天在本地（电信），阿里云vps（杭州数据中心），国外vps（美国加州数据中心），国外独服（荷兰数据中心）测试，无一例外都爆出了这种错误。
而我在用浏览器上传一个18GB的备份文件时，最终成功上传。

**Comment by Aruelius** [comment]
> 我今天在本地（电信），阿里云vps（杭州数据中心），国外vps（美国加州数据中心），国外独服（荷兰数据中心）测试，无一例外都爆出了这种错误。
> 而我在用浏览器上传一个18GB的备份文件时，最终成功上传。

说明上传确实写的有问题。

**Comment by Lip136** [comment]
作者你好，
       我也遇到同样的问题了，我感觉是上传太多了的原因？？

**Comment by Aruelius** [comment]
> 作者你好，
> 我也遇到同样的问题了，我感觉是上传太多了的原因？？

是程序问题，后续会解决的。

**Comment by canwushuang** [comment]
应该是requests toolbelt的问题。感觉有点难解决该问题

**Comment by hais1992** [comment]
是也遇到了这问题，上传2.5G 的文件也基本上100%出错~ 多次尝试都传不上去。
